version: '3'
services:

  web:
    platform: linux/amd64
    build:
      context: .
      dockerfile: deploy/web/Dockerfile
    container_name: guiexpert
    command: nginx-debug -g 'daemon off;'
    ports:
      - '80:80'
      - '443:443'

