import { ColumnDefIf, SelectionModel, TableModelAndOptionsIf, TreeRow } from '../../../../table/src';
import { PersonIf } from "./person.if";
export declare function createTreePeopleTableOptions(addDemoSelection?: boolean): {
    hoverColumnVisible: boolean;
    defaultRowHeights: {
        header: number;
        body: number;
        footer: number;
    };
    autoRestoreOptions: {
        getStorageKeyFn: () => string;
        autoRestoreCollapsedExpandedState: boolean;
        autoRestoreScrollPosition: boolean;
        autoRestoreSortingState: boolean;
        autoRestoreCheckedState: boolean;
        autoRestoreSelectedState: boolean;
        isSame: (r1: PersonIf, r2: PersonIf, options: import('../../../../table/src').AutoRestoreOptionsIf<PersonIf>) => boolean;
        getRowId: (row: PersonIf) => string | number;
    };
    externalFilterFunction: (_value: TreeRow<PersonIf>, _index: number, _array: PersonIf[]) => boolean;
    getSelectionModel: () => SelectionModel;
    overflowX: "auto" | "scroll";
    overflowY: "auto" | "scroll";
    horizontalBorderVisible: boolean;
    verticalBorderVisible: boolean;
    footerSeparatorBorderVisible: boolean;
    headerSeparatorBorderVisible: boolean;
    fixedEastSeparatorBorderVisible: boolean;
    fixedWestSeparatorBorderVisible: boolean;
    tableTopBorderVisible: boolean;
    tableBottomBorderVisible: boolean;
    hoverRowVisible: boolean;
    columnsResizable: boolean;
    columnsDraggable: boolean;
    columnResizeHandleWidthInPx: number;
    footerVerticalSeparator: boolean;
    headerToggleExpandCollapseIcons: boolean;
    headerVerticalSeparator: boolean;
    treeOptions: import('../../../../table/src').TreeOptions;
    headerGroupOptions: import("packages/table/src/lib/table/data/options/header-group-options").HeaderGroupOptions;
    showCheckboxWihoutExtraColumn: boolean;
    sortedOptions: import('../../../../table/src').SortedOptions;
    sortOrder: import('../../../../table/src').SortState[];
    shortcutActionIdMapping?: import('../../../../table/src').ShortcutActionIdMapping | undefined;
    resizeEventDebounceDelay: number;
    getEditRenderer?: import('../../../../table/src').GetEditRenderer | undefined;
    getFocusModel?: import('../../../../table/src').GetT<import('../../../../table/src').FocusModelIf> | undefined;
};
export declare function createTreePeopleColumnDefs(): ColumnDefIf[];
export declare function createTreePeopleModelAndOptions(addDemoSelection?: boolean): TableModelAndOptionsIf;
