
import {OrderIf} from "../model/order.if";


/**
 * https://app.json-generator.com/DdnuC-lobzBN
 *
 * JG.repeat(5, 205, {
 *   id: JG.objectId().substring(17,19) + '-' + JG.objectId().substring(10,16),
 *   company: JG.company(),
 *   country: JG.country(),
 *   product: JG.lastName(),
 *   sellDate: moment(JG.date(new Date(2023, 0, 1),
 *                            new Date(2023, 10, 1))).format('YYYY-MM-DD'),
 *   inStock: !!JG.integer(0, 1),
 *   quantity: JG.integer(1, 100),
 *   progress: JG.integer(1, 5),
 *   rating: JG.integer(1, 5)
 * });
 */
const data: OrderIf[] = [
  {
    "id": "c8-34f1d5",
    "company": "Equicom",
    "country": "Gibraltar",
    "product": "May",
    "sellDate": "2023-09-23",
    "inStock": false,
    "quantity": 55,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "8c-bd6321",
    "company": "Cognicode",
    "country": "Christmas Island",
    "product": "Cash",
    "sellDate": "2023-03-27",
    "inStock": false,
    "quantity": 87,
    "progress": 2,
    "rating": 5
  },
  {
    "id": "c0-965ff8",
    "company": "Makingway",
    "country": "Guinea",
    "product": "Stuart",
    "sellDate": "2023-06-30",
    "inStock": false,
    "quantity": 74,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "65-0d10f5",
    "company": "Accruex",
    "country": "Dominica",
    "product": "Mcbride",
    "sellDate": "2023-01-12",
    "inStock": false,
    "quantity": 21,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "e3-0fd973",
    "company": "Ronelon",
    "country": "Fiji",
    "product": "Hull",
    "sellDate": "2023-06-03",
    "inStock": false,
    "quantity": 42,
    "progress": 2,
    "rating": 5
  },
  {
    "id": "1e-89aa63",
    "company": "Letpro",
    "country": "Gabon",
    "product": "Parker",
    "sellDate": "2023-04-15",
    "inStock": false,
    "quantity": 24,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "cc-01588d",
    "company": "Keeg",
    "country": "Cameroon",
    "product": "Ryan",
    "sellDate": "2023-09-03",
    "inStock": true,
    "quantity": 95,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "56-6b3a96",
    "company": "Hinway",
    "country": "Finland",
    "product": "Calhoun",
    "sellDate": "2023-07-24",
    "inStock": false,
    "quantity": 33,
    "progress": 4,
    "rating": 3
  },
  {
    "id": "19-d0709b",
    "company": "Keengen",
    "country": "Martinique",
    "product": "Bradshaw",
    "sellDate": "2023-05-27",
    "inStock": false,
    "quantity": 87,
    "progress": 4,
    "rating": 3
  },
  {
    "id": "c7-9aafc4",
    "company": "Jamnation",
    "country": "Pitcairn",
    "product": "Pratt",
    "sellDate": "2023-01-13",
    "inStock": false,
    "quantity": 22,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "e6-c3bd28",
    "company": "Repetwire",
    "country": "Mozambique",
    "product": "Callahan",
    "sellDate": "2023-04-22",
    "inStock": true,
    "quantity": 97,
    "progress": 3,
    "rating": 1
  },
  {
    "id": "49-4fead0",
    "company": "Scentric",
    "country": "China",
    "product": "Hill",
    "sellDate": "2023-09-21",
    "inStock": false,
    "quantity": 97,
    "progress": 5,
    "rating": 5
  },
  {
    "id": "82-345bba",
    "company": "Bizmatic",
    "country": "Romania",
    "product": "Cooke",
    "sellDate": "2023-04-06",
    "inStock": false,
    "quantity": 64,
    "progress": 2,
    "rating": 2
  },
  {
    "id": "c7-ec3ec2",
    "company": "Apexia",
    "country": "Lesotho",
    "product": "Mckenzie",
    "sellDate": "2023-06-12",
    "inStock": true,
    "quantity": 1,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "a7-d09e56",
    "company": "Polarax",
    "country": "Kuwait",
    "product": "Fox",
    "sellDate": "2023-05-15",
    "inStock": false,
    "quantity": 70,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "48-42993b",
    "company": "Pheast",
    "country": "Cape Verde",
    "product": "York",
    "sellDate": "2023-04-06",
    "inStock": false,
    "quantity": 25,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "78-f32d5f",
    "company": "Rodeocean",
    "country": "United Kingdom",
    "product": "Hawkins",
    "sellDate": "2023-07-02",
    "inStock": false,
    "quantity": 1,
    "progress": 1,
    "rating": 4
  },
  {
    "id": "76-a12b6d",
    "company": "Kage",
    "country": "Tanzania",
    "product": "Arnold",
    "sellDate": "2023-09-08",
    "inStock": false,
    "quantity": 50,
    "progress": 2,
    "rating": 2
  },
  {
    "id": "fb-c88d47",
    "company": "Exoswitch",
    "country": "Botswana",
    "product": "Rivers",
    "sellDate": "2023-10-07",
    "inStock": true,
    "quantity": 84,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "84-e729cd",
    "company": "Isologics",
    "country": "Panama",
    "product": "Burks",
    "sellDate": "2023-07-12",
    "inStock": true,
    "quantity": 17,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "29-7f5ba3",
    "company": "Joviold",
    "country": "Macedonia",
    "product": "Fitzpatrick",
    "sellDate": "2023-06-30",
    "inStock": false,
    "quantity": 26,
    "progress": 3,
    "rating": 3
  },
  {
    "id": "57-8d0ecb",
    "company": "Anarco",
    "country": "Yugoslavia",
    "product": "Hurley",
    "sellDate": "2023-07-03",
    "inStock": false,
    "quantity": 89,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "87-50f99d",
    "company": "Apex",
    "country": "Syria",
    "product": "Cummings",
    "sellDate": "2023-05-07",
    "inStock": false,
    "quantity": 48,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "18-fcf243",
    "company": "Decratex",
    "country": "Marshall Islands",
    "product": "Freeman",
    "sellDate": "2023-06-29",
    "inStock": true,
    "quantity": 46,
    "progress": 5,
    "rating": 2
  },
  {
    "id": "ab-04ba2d",
    "company": "Aquoavo",
    "country": "Haiti",
    "product": "Gilbert",
    "sellDate": "2023-09-22",
    "inStock": false,
    "quantity": 1,
    "progress": 3,
    "rating": 1
  },
  {
    "id": "2d-d80b66",
    "company": "Turnabout",
    "country": "Estonia",
    "product": "Foley",
    "sellDate": "2023-05-31",
    "inStock": false,
    "quantity": 24,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "07-07a4ba",
    "company": "Pyrami",
    "country": "Benin",
    "product": "Greene",
    "sellDate": "2023-06-19",
    "inStock": false,
    "quantity": 28,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "4f-7a2053",
    "company": "Pulze",
    "country": "Switzerland",
    "product": "Keller",
    "sellDate": "2023-01-07",
    "inStock": true,
    "quantity": 51,
    "progress": 4,
    "rating": 4
  },
  {
    "id": "72-3c1206",
    "company": "Avit",
    "country": "Indonesia",
    "product": "Hayes",
    "sellDate": "2023-03-17",
    "inStock": true,
    "quantity": 82,
    "progress": 1,
    "rating": 1
  },
  {
    "id": "8c-a89457",
    "company": "Malathion",
    "country": "Uganda",
    "product": "Quinn",
    "sellDate": "2023-03-11",
    "inStock": true,
    "quantity": 36,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "85-bf0183",
    "company": "Peticular",
    "country": "Puerto Rico",
    "product": "Sanchez",
    "sellDate": "2023-06-11",
    "inStock": true,
    "quantity": 1,
    "progress": 1,
    "rating": 2
  },
  {
    "id": "b8-be979f",
    "company": "Uni",
    "country": "Kenya",
    "product": "Wilkins",
    "sellDate": "2023-01-22",
    "inStock": true,
    "quantity": 91,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "34-369401",
    "company": "Zaya",
    "country": "French Guiana",
    "product": "Sanford",
    "sellDate": "2023-08-20",
    "inStock": false,
    "quantity": 28,
    "progress": 1,
    "rating": 4
  },
  {
    "id": "d5-4a5861",
    "company": "Eyewax",
    "country": "United States",
    "product": "Baird",
    "sellDate": "2023-07-08",
    "inStock": true,
    "quantity": 20,
    "progress": 2,
    "rating": 4
  },
  {
    "id": "b5-bbc6f7",
    "company": "Fangold",
    "country": "Morocco",
    "product": "Coffey",
    "sellDate": "2023-07-23",
    "inStock": true,
    "quantity": 95,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "22-ee5001",
    "company": "Comtour",
    "country": "Brazil",
    "product": "Bray",
    "sellDate": "2023-05-20",
    "inStock": true,
    "quantity": 20,
    "progress": 2,
    "rating": 4
  },
  {
    "id": "ee-8bf1f6",
    "company": "Synkgen",
    "country": "Bhutan",
    "product": "Page",
    "sellDate": "2023-01-08",
    "inStock": true,
    "quantity": 74,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "05-863f3a",
    "company": "Quordate",
    "country": "Bolivia",
    "product": "Sweet",
    "sellDate": "2023-09-05",
    "inStock": true,
    "quantity": 62,
    "progress": 2,
    "rating": 4
  },
  {
    "id": "bd-ea3a40",
    "company": "Isbol",
    "country": "Costa Rica",
    "product": "Monroe",
    "sellDate": "2023-03-31",
    "inStock": false,
    "quantity": 92,
    "progress": 1,
    "rating": 1
  },
  {
    "id": "95-b5af05",
    "company": "Confrenzy",
    "country": "Jordan",
    "product": "Haney",
    "sellDate": "2023-03-22",
    "inStock": false,
    "quantity": 19,
    "progress": 4,
    "rating": 3
  },
  {
    "id": "33-b40a77",
    "company": "Zolar",
    "country": "Ecuador",
    "product": "Clements",
    "sellDate": "2023-01-28",
    "inStock": true,
    "quantity": 3,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "41-33f3a7",
    "company": "Liquidoc",
    "country": "Bosnia and Herzegovina",
    "product": "Wiley",
    "sellDate": "2023-05-06",
    "inStock": false,
    "quantity": 59,
    "progress": 2,
    "rating": 4
  },
  {
    "id": "af-43fffe",
    "company": "Delphide",
    "country": "Algeria",
    "product": "Gilliam",
    "sellDate": "2023-05-20",
    "inStock": true,
    "quantity": 4,
    "progress": 3,
    "rating": 5
  },
  {
    "id": "40-1992e6",
    "company": "Zenco",
    "country": "Tuvalu",
    "product": "Meadows",
    "sellDate": "2023-04-23",
    "inStock": false,
    "quantity": 88,
    "progress": 4,
    "rating": 2
  },
  {
    "id": "29-5f2d93",
    "company": "Manufact",
    "country": "Italy",
    "product": "Sims",
    "sellDate": "2023-07-19",
    "inStock": true,
    "quantity": 41,
    "progress": 5,
    "rating": 2
  },
  {
    "id": "96-be95a9",
    "company": "Futuris",
    "country": "Egypt",
    "product": "Higgins",
    "sellDate": "2023-05-18",
    "inStock": true,
    "quantity": 7,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "46-c5822c",
    "company": "Biolive",
    "country": "Tonga",
    "product": "Gordon",
    "sellDate": "2023-07-16",
    "inStock": true,
    "quantity": 26,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "97-88eaaf",
    "company": "Comstar",
    "country": "Bermuda",
    "product": "Campbell",
    "sellDate": "2023-01-11",
    "inStock": true,
    "quantity": 13,
    "progress": 2,
    "rating": 4
  },
  {
    "id": "bb-2e51e5",
    "company": "Opticon",
    "country": "Viet Nam",
    "product": "Boyle",
    "sellDate": "2023-06-21",
    "inStock": false,
    "quantity": 3,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "d1-46e472",
    "company": "Netility",
    "country": "United Arab Emirates",
    "product": "Hensley",
    "sellDate": "2023-10-01",
    "inStock": true,
    "quantity": 90,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "dc-9282b9",
    "company": "Printspan",
    "country": "Saint Vincent and The Grenadines",
    "product": "Francis",
    "sellDate": "2023-10-24",
    "inStock": false,
    "quantity": 64,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "44-1c6347",
    "company": "Dancity",
    "country": "Argentina",
    "product": "Chen",
    "sellDate": "2023-02-22",
    "inStock": false,
    "quantity": 16,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "0e-d69ba5",
    "company": "Ecolight",
    "country": "Andorra",
    "product": "Gibbs",
    "sellDate": "2023-04-08",
    "inStock": true,
    "quantity": 41,
    "progress": 4,
    "rating": 4
  },
  {
    "id": "0c-12dcee",
    "company": "Bunga",
    "country": "French Polynesia",
    "product": "Hicks",
    "sellDate": "2023-02-10",
    "inStock": true,
    "quantity": 31,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "d9-f6a550",
    "company": "Mediot",
    "country": "Poland",
    "product": "Vazquez",
    "sellDate": "2023-02-26",
    "inStock": false,
    "quantity": 86,
    "progress": 3,
    "rating": 5
  },
  {
    "id": "e2-5bbbac",
    "company": "Acumentor",
    "country": "Liechtenstein",
    "product": "Flowers",
    "sellDate": "2023-01-10",
    "inStock": false,
    "quantity": 18,
    "progress": 1,
    "rating": 1
  },
  {
    "id": "4a-483505",
    "company": "Vendblend",
    "country": "Turkey",
    "product": "Gaines",
    "sellDate": "2023-03-06",
    "inStock": true,
    "quantity": 50,
    "progress": 2,
    "rating": 5
  },
  {
    "id": "d1-798f3e",
    "company": "Radiantix",
    "country": "Seychelles",
    "product": "Chan",
    "sellDate": "2023-10-08",
    "inStock": true,
    "quantity": 93,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "3f-95a1b2",
    "company": "Zolarity",
    "country": "Philippines",
    "product": "Elliott",
    "sellDate": "2023-01-30",
    "inStock": true,
    "quantity": 1,
    "progress": 3,
    "rating": 5
  },
  {
    "id": "5f-701839",
    "company": "Twiggery",
    "country": "Togo",
    "product": "Daniel",
    "sellDate": "2023-04-05",
    "inStock": false,
    "quantity": 41,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "9b-9520df",
    "company": "Tasmania",
    "country": "Greenland",
    "product": "Newton",
    "sellDate": "2023-07-11",
    "inStock": false,
    "quantity": 15,
    "progress": 3,
    "rating": 1
  },
  {
    "id": "e0-2252b2",
    "company": "Exodoc",
    "country": "Saint Lucia",
    "product": "Juarez",
    "sellDate": "2023-10-19",
    "inStock": true,
    "quantity": 45,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "13-2fdfdd",
    "company": "Geekular",
    "country": "Dominican Republic",
    "product": "Boyd",
    "sellDate": "2023-10-18",
    "inStock": false,
    "quantity": 58,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "82-7b4f5a",
    "company": "Sealoud",
    "country": "Cote D'Ivoire (Ivory Coast)",
    "product": "Irwin",
    "sellDate": "2023-10-20",
    "inStock": true,
    "quantity": 39,
    "progress": 1,
    "rating": 5
  },
  {
    "id": "24-26d884",
    "company": "Uberlux",
    "country": "New Zealand",
    "product": "Whitaker",
    "sellDate": "2023-07-10",
    "inStock": false,
    "quantity": 37,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "10-9ae141",
    "company": "Plasmos",
    "country": "Ireland",
    "product": "Schroeder",
    "sellDate": "2023-02-22",
    "inStock": false,
    "quantity": 11,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "f6-cac573",
    "company": "Zilencio",
    "country": "Wallis and Futuna Islands",
    "product": "Crawford",
    "sellDate": "2023-02-06",
    "inStock": true,
    "quantity": 57,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "ed-afd34c",
    "company": "Polaria",
    "country": "Norfolk Island",
    "product": "Sandoval",
    "sellDate": "2023-08-26",
    "inStock": false,
    "quantity": 74,
    "progress": 2,
    "rating": 5
  },
  {
    "id": "5f-751138",
    "company": "Insurity",
    "country": "Laos",
    "product": "Wall",
    "sellDate": "2023-09-29",
    "inStock": true,
    "quantity": 34,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "1f-5e4389",
    "company": "Cyclonica",
    "country": "Belarus",
    "product": "Chase",
    "sellDate": "2023-10-26",
    "inStock": false,
    "quantity": 55,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "85-1d3537",
    "company": "Namebox",
    "country": "Guatemala",
    "product": "Beach",
    "sellDate": "2023-05-21",
    "inStock": false,
    "quantity": 81,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "51-e4ebe7",
    "company": "Callflex",
    "country": "Faroe Islands",
    "product": "Saunders",
    "sellDate": "2023-03-13",
    "inStock": true,
    "quantity": 53,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "93-772d3f",
    "company": "Farmex",
    "country": "Netherlands",
    "product": "Reeves",
    "sellDate": "2023-08-18",
    "inStock": false,
    "quantity": 80,
    "progress": 1,
    "rating": 5
  },
  {
    "id": "fb-67174c",
    "company": "Geekology",
    "country": "Equatorial Guinea",
    "product": "Dillard",
    "sellDate": "2023-05-10",
    "inStock": true,
    "quantity": 97,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "3e-4345d3",
    "company": "Springbee",
    "country": "Korea (South)",
    "product": "Walton",
    "sellDate": "2023-01-14",
    "inStock": false,
    "quantity": 3,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "fe-3ece97",
    "company": "Terascape",
    "country": "Venezuela",
    "product": "Johnston",
    "sellDate": "2023-04-28",
    "inStock": false,
    "quantity": 62,
    "progress": 5,
    "rating": 2
  },
  {
    "id": "d1-249332",
    "company": "Exposa",
    "country": "Israel",
    "product": "Parrish",
    "sellDate": "2023-07-31",
    "inStock": false,
    "quantity": 86,
    "progress": 1,
    "rating": 1
  },
  {
    "id": "81-01bf85",
    "company": "Zidox",
    "country": "Sri Lanka",
    "product": "Goodwin",
    "sellDate": "2023-03-28",
    "inStock": false,
    "quantity": 40,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "cc-079f50",
    "company": "Bostonic",
    "country": "French Southern Territories",
    "product": "Lee",
    "sellDate": "2023-06-21",
    "inStock": true,
    "quantity": 31,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "71-a38a87",
    "company": "Beadzza",
    "country": "Myanmar",
    "product": "Knox",
    "sellDate": "2023-05-14",
    "inStock": true,
    "quantity": 15,
    "progress": 3,
    "rating": 2
  },
  {
    "id": "87-81afa4",
    "company": "Elita",
    "country": "Guinea-Bissau",
    "product": "Fletcher",
    "sellDate": "2023-08-13",
    "inStock": false,
    "quantity": 78,
    "progress": 3,
    "rating": 5
  },
  {
    "id": "70-1879c6",
    "company": "Visalia",
    "country": "Mauritius",
    "product": "Conway",
    "sellDate": "2023-04-21",
    "inStock": false,
    "quantity": 49,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "61-1f8736",
    "company": "Brainclip",
    "country": "Iraq",
    "product": "Wilkinson",
    "sellDate": "2023-05-07",
    "inStock": false,
    "quantity": 53,
    "progress": 2,
    "rating": 5
  },
  {
    "id": "72-63f266",
    "company": "Andershun",
    "country": "Sierra Leone",
    "product": "House",
    "sellDate": "2023-10-09",
    "inStock": true,
    "quantity": 96,
    "progress": 3,
    "rating": 5
  },
  {
    "id": "d4-2011d0",
    "company": "Geeknet",
    "country": "Guyana",
    "product": "Marshall",
    "sellDate": "2023-06-08",
    "inStock": false,
    "quantity": 22,
    "progress": 4,
    "rating": 3
  },
  {
    "id": "cd-afe06c",
    "company": "Zanymax",
    "country": "Denmark",
    "product": "Ferrell",
    "sellDate": "2023-03-08",
    "inStock": true,
    "quantity": 40,
    "progress": 3,
    "rating": 3
  },
  {
    "id": "4d-a71192",
    "company": "Oatfarm",
    "country": "Heard and McDonald Islands",
    "product": "Jarvis",
    "sellDate": "2023-02-08",
    "inStock": false,
    "quantity": 52,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "d0-101404",
    "company": "Wazzu",
    "country": "Sweden",
    "product": "Wilder",
    "sellDate": "2023-03-25",
    "inStock": false,
    "quantity": 94,
    "progress": 3,
    "rating": 1
  },
  {
    "id": "a8-a39f02",
    "company": "Sensate",
    "country": "Malta",
    "product": "Carpenter",
    "sellDate": "2023-09-13",
    "inStock": true,
    "quantity": 90,
    "progress": 3,
    "rating": 3
  },
  {
    "id": "1e-6f4e9d",
    "company": "Undertap",
    "country": "Belgium",
    "product": "Garcia",
    "sellDate": "2023-05-02",
    "inStock": false,
    "quantity": 51,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "56-7d7bc2",
    "company": "Scenty",
    "country": "Kyrgyzstan",
    "product": "Lewis",
    "sellDate": "2023-02-01",
    "inStock": true,
    "quantity": 38,
    "progress": 3,
    "rating": 2
  },
  {
    "id": "86-257d3b",
    "company": "Slofast",
    "country": "Thailand",
    "product": "Vega",
    "sellDate": "2023-04-06",
    "inStock": false,
    "quantity": 95,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "71-800db9",
    "company": "Buzzworks",
    "country": "Honduras",
    "product": "Kinney",
    "sellDate": "2023-09-15",
    "inStock": true,
    "quantity": 55,
    "progress": 2,
    "rating": 4
  },
  {
    "id": "1b-929b2e",
    "company": "Tubesys",
    "country": "Cyprus",
    "product": "Hale",
    "sellDate": "2023-07-18",
    "inStock": true,
    "quantity": 82,
    "progress": 3,
    "rating": 1
  },
  {
    "id": "57-fd7ff2",
    "company": "Teraprene",
    "country": "Colombia",
    "product": "Sellers",
    "sellDate": "2023-10-19",
    "inStock": true,
    "quantity": 44,
    "progress": 2,
    "rating": 5
  },
  {
    "id": "73-b5c814",
    "company": "Katakana",
    "country": "Mali",
    "product": "Long",
    "sellDate": "2023-06-15",
    "inStock": false,
    "quantity": 90,
    "progress": 3,
    "rating": 3
  },
  {
    "id": "a6-d46323",
    "company": "Buzzopia",
    "country": "Falkland Islands (Malvinas)",
    "product": "Mcdaniel",
    "sellDate": "2023-04-06",
    "inStock": false,
    "quantity": 8,
    "progress": 1,
    "rating": 5
  },
  {
    "id": "c0-8896f2",
    "company": "Comtest",
    "country": "Tunisia",
    "product": "Walls",
    "sellDate": "2023-05-07",
    "inStock": true,
    "quantity": 20,
    "progress": 4,
    "rating": 4
  },
  {
    "id": "83-e80230",
    "company": "Lyria",
    "country": "Saudi Arabia",
    "product": "Davidson",
    "sellDate": "2023-08-06",
    "inStock": true,
    "quantity": 29,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "f1-404878",
    "company": "Xerex",
    "country": "Angola",
    "product": "Frank",
    "sellDate": "2023-08-08",
    "inStock": true,
    "quantity": 91,
    "progress": 4,
    "rating": 3
  },
  {
    "id": "18-09176f",
    "company": "Toyletry",
    "country": "Belize",
    "product": "Barrera",
    "sellDate": "2023-07-20",
    "inStock": false,
    "quantity": 32,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "b4-6ec10d",
    "company": "Bezal",
    "country": "Swaziland",
    "product": "Burton",
    "sellDate": "2023-06-10",
    "inStock": false,
    "quantity": 37,
    "progress": 2,
    "rating": 2
  },
  {
    "id": "0d-508dc9",
    "company": "Dancerity",
    "country": "Reunion",
    "product": "Robinson",
    "sellDate": "2023-10-24",
    "inStock": false,
    "quantity": 5,
    "progress": 3,
    "rating": 5
  },
  {
    "id": "29-f12861",
    "company": "Bolax",
    "country": "Grenada",
    "product": "Kerr",
    "sellDate": "2023-08-07",
    "inStock": false,
    "quantity": 38,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "de-f686ed",
    "company": "Quonata",
    "country": "Cayman Islands",
    "product": "Kemp",
    "sellDate": "2023-04-06",
    "inStock": false,
    "quantity": 54,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "75-bb9256",
    "company": "Insuresys",
    "country": "Paraguay",
    "product": "Norris",
    "sellDate": "2023-06-05",
    "inStock": true,
    "quantity": 73,
    "progress": 3,
    "rating": 1
  },
  {
    "id": "1b-d23942",
    "company": "Earthwax",
    "country": "Hong Kong",
    "product": "James",
    "sellDate": "2023-03-03",
    "inStock": false,
    "quantity": 59,
    "progress": 4,
    "rating": 4
  },
  {
    "id": "55-6b9927",
    "company": "Wrapture",
    "country": "Niue",
    "product": "Hayden",
    "sellDate": "2023-07-21",
    "inStock": true,
    "quantity": 99,
    "progress": 1,
    "rating": 5
  },
  {
    "id": "5d-0cdbd8",
    "company": "Stucco",
    "country": "Nauru",
    "product": "William",
    "sellDate": "2023-05-09",
    "inStock": false,
    "quantity": 88,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "b4-0b7371",
    "company": "Soprano",
    "country": "Bouvet Island",
    "product": "Ingram",
    "sellDate": "2023-04-12",
    "inStock": false,
    "quantity": 84,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "26-ff1f20",
    "company": "Zosis",
    "country": "Trinidad and Tobago",
    "product": "Duffy",
    "sellDate": "2023-09-29",
    "inStock": false,
    "quantity": 32,
    "progress": 2,
    "rating": 5
  },
  {
    "id": "65-d6b672",
    "company": "Digigene",
    "country": "Latvia",
    "product": "Mcmahon",
    "sellDate": "2023-01-15",
    "inStock": false,
    "quantity": 17,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "06-662dce",
    "company": "Flexigen",
    "country": "Antarctica",
    "product": "Cameron",
    "sellDate": "2023-01-03",
    "inStock": false,
    "quantity": 79,
    "progress": 1,
    "rating": 1
  },
  {
    "id": "ed-db4290",
    "company": "Zytrex",
    "country": "Vatican City State (Holy See)",
    "product": "Guerrero",
    "sellDate": "2023-01-24",
    "inStock": false,
    "quantity": 38,
    "progress": 1,
    "rating": 5
  },
  {
    "id": "38-32ac19",
    "company": "Centuria",
    "country": "Tokelau",
    "product": "Rios",
    "sellDate": "2023-04-21",
    "inStock": true,
    "quantity": 75,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "e0-1296cc",
    "company": "Quantasis",
    "country": "St. Pierre and Miquelon",
    "product": "Hardin",
    "sellDate": "2023-08-30",
    "inStock": true,
    "quantity": 80,
    "progress": 1,
    "rating": 3
  },
  {
    "id": "d5-66000a",
    "company": "Interodeo",
    "country": "Pakistan",
    "product": "Horn",
    "sellDate": "2023-08-26",
    "inStock": false,
    "quantity": 78,
    "progress": 1,
    "rating": 1
  },
  {
    "id": "b4-f5be36",
    "company": "Lyrichord",
    "country": "S. Georgia and S. Sandwich Isls.",
    "product": "Jimenez",
    "sellDate": "2023-06-18",
    "inStock": true,
    "quantity": 82,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "20-6ca674",
    "company": "Unisure",
    "country": "Cook Islands",
    "product": "Ramirez",
    "sellDate": "2023-03-04",
    "inStock": false,
    "quantity": 18,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "2a-4a3022",
    "company": "Portica",
    "country": "Monaco",
    "product": "Moran",
    "sellDate": "2023-05-27",
    "inStock": true,
    "quantity": 40,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "2d-fba967",
    "company": "Neocent",
    "country": "Djibouti",
    "product": "Knapp",
    "sellDate": "2023-07-07",
    "inStock": true,
    "quantity": 30,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "92-52ccab",
    "company": "Koffee",
    "country": "Mexico",
    "product": "Stephens",
    "sellDate": "2023-09-02",
    "inStock": true,
    "quantity": 67,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "85-145471",
    "company": "Skinserve",
    "country": "Bahrain",
    "product": "Yates",
    "sellDate": "2023-08-23",
    "inStock": false,
    "quantity": 24,
    "progress": 4,
    "rating": 4
  },
  {
    "id": "77-5d4054",
    "company": "Extragene",
    "country": "Albania",
    "product": "Chambers",
    "sellDate": "2023-08-01",
    "inStock": true,
    "quantity": 88,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "77-05cab0",
    "company": "Medcom",
    "country": "Palau",
    "product": "Buckley",
    "sellDate": "2023-08-10",
    "inStock": true,
    "quantity": 61,
    "progress": 4,
    "rating": 1
  },
  {
    "id": "eb-95464f",
    "company": "Exotechno",
    "country": "Cocos (Keeling Islands)",
    "product": "Griffith",
    "sellDate": "2023-03-28",
    "inStock": false,
    "quantity": 30,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "be-ef4295",
    "company": "Animalia",
    "country": "Lebanon",
    "product": "Kirby",
    "sellDate": "2023-04-30",
    "inStock": false,
    "quantity": 14,
    "progress": 1,
    "rating": 4
  },
  {
    "id": "a3-2a83a5",
    "company": "Combogene",
    "country": "Western Sahara",
    "product": "Sampson",
    "sellDate": "2023-08-26",
    "inStock": false,
    "quantity": 44,
    "progress": 1,
    "rating": 4
  },
  {
    "id": "6a-4e94b0",
    "company": "Junipoor",
    "country": "Gambia",
    "product": "Phillips",
    "sellDate": "2023-10-03",
    "inStock": false,
    "quantity": 89,
    "progress": 3,
    "rating": 3
  },
  {
    "id": "33-f72672",
    "company": "Accuprint",
    "country": "Aruba",
    "product": "Peters",
    "sellDate": "2023-09-05",
    "inStock": false,
    "quantity": 95,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "6b-dacaa8",
    "company": "Geekko",
    "country": "Japan",
    "product": "Fitzgerald",
    "sellDate": "2023-02-03",
    "inStock": true,
    "quantity": 35,
    "progress": 2,
    "rating": 5
  },
  {
    "id": "bc-1f5c29",
    "company": "Xumonk",
    "country": "Maldives",
    "product": "Hunter",
    "sellDate": "2023-09-02",
    "inStock": false,
    "quantity": 62,
    "progress": 3,
    "rating": 2
  },
  {
    "id": "e2-02aeaf",
    "company": "Qot",
    "country": "Kazakhstan",
    "product": "Turner",
    "sellDate": "2023-06-21",
    "inStock": true,
    "quantity": 63,
    "progress": 3,
    "rating": 3
  },
  {
    "id": "fb-886995",
    "company": "Nebulean",
    "country": "Malawi",
    "product": "Robbins",
    "sellDate": "2023-06-02",
    "inStock": false,
    "quantity": 10,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "e7-318de0",
    "company": "Sultrax",
    "country": "Chad",
    "product": "Hart",
    "sellDate": "2023-10-27",
    "inStock": true,
    "quantity": 1,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "47-b96571",
    "company": "Savvy",
    "country": "East Timor",
    "product": "Chang",
    "sellDate": "2023-10-17",
    "inStock": false,
    "quantity": 19,
    "progress": 5,
    "rating": 5
  },
  {
    "id": "e8-dcc211",
    "company": "Kaggle",
    "country": "Taiwan",
    "product": "Rodriguez",
    "sellDate": "2023-08-19",
    "inStock": false,
    "quantity": 58,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "49-baa16c",
    "company": "Cosmosis",
    "country": "Macau",
    "product": "Petersen",
    "sellDate": "2023-09-05",
    "inStock": false,
    "quantity": 38,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "ec-ecb801",
    "company": "Pushcart",
    "country": "Zambia",
    "product": "Hess",
    "sellDate": "2023-04-07",
    "inStock": false,
    "quantity": 30,
    "progress": 4,
    "rating": 4
  },
  {
    "id": "1f-8ac559",
    "company": "Homelux",
    "country": "Georgia",
    "product": "Bass",
    "sellDate": "2023-07-01",
    "inStock": true,
    "quantity": 81,
    "progress": 1,
    "rating": 3
  },
  {
    "id": "21-d5f6fc",
    "company": "Verton",
    "country": "Montserrat",
    "product": "Steele",
    "sellDate": "2023-08-26",
    "inStock": false,
    "quantity": 70,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "ff-1f08b6",
    "company": "Boilcat",
    "country": "Austria",
    "product": "Farmer",
    "sellDate": "2023-01-29",
    "inStock": false,
    "quantity": 68,
    "progress": 3,
    "rating": 2
  },
  {
    "id": "a7-8b26de",
    "company": "Equitax",
    "country": "Cambodia",
    "product": "Giles",
    "sellDate": "2023-01-03",
    "inStock": true,
    "quantity": 33,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "a8-cfed2a",
    "company": "Emtrak",
    "country": "Croatia (Hrvatska)",
    "product": "Martin",
    "sellDate": "2023-06-27",
    "inStock": true,
    "quantity": 47,
    "progress": 1,
    "rating": 3
  },
  {
    "id": "ae-f7c266",
    "company": "Opticall",
    "country": "Mauritania",
    "product": "Graham",
    "sellDate": "2023-06-14",
    "inStock": false,
    "quantity": 31,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "aa-f61694",
    "company": "Futurize",
    "country": "Uruguay",
    "product": "Solis",
    "sellDate": "2023-01-19",
    "inStock": false,
    "quantity": 31,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "9a-6b120d",
    "company": "Klugger",
    "country": "Ukraine",
    "product": "Brennan",
    "sellDate": "2023-04-14",
    "inStock": false,
    "quantity": 67,
    "progress": 4,
    "rating": 2
  },
  {
    "id": "b2-e55f22",
    "company": "Nitracyr",
    "country": "Chile",
    "product": "Ortega",
    "sellDate": "2023-05-15",
    "inStock": false,
    "quantity": 67,
    "progress": 4,
    "rating": 2
  },
  {
    "id": "49-dcc29a",
    "company": "Caxt",
    "country": "Yemen",
    "product": "Snow",
    "sellDate": "2023-08-09",
    "inStock": false,
    "quantity": 66,
    "progress": 3,
    "rating": 3
  },
  {
    "id": "48-327ba4",
    "company": "Zensure",
    "country": "Papua New Guinea",
    "product": "Swanson",
    "sellDate": "2023-07-03",
    "inStock": true,
    "quantity": 81,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "78-a4d294",
    "company": "Quintity",
    "country": "Hungary",
    "product": "Patton",
    "sellDate": "2023-02-20",
    "inStock": false,
    "quantity": 70,
    "progress": 3,
    "rating": 2
  },
  {
    "id": "3b-658f74",
    "company": "Stelaecor",
    "country": "Tajikistan",
    "product": "Ford",
    "sellDate": "2023-08-31",
    "inStock": false,
    "quantity": 89,
    "progress": 2,
    "rating": 1
  },
  {
    "id": "7f-05f54c",
    "company": "Voratak",
    "country": "Spain",
    "product": "Collier",
    "sellDate": "2023-04-16",
    "inStock": false,
    "quantity": 79,
    "progress": 5,
    "rating": 4
  },
  {
    "id": "50-992dbc",
    "company": "Comstruct",
    "country": "Iceland",
    "product": "Atkinson",
    "sellDate": "2023-09-15",
    "inStock": false,
    "quantity": 99,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "27-f0a446",
    "company": "Egypto",
    "country": "Russian Federation",
    "product": "Mcgowan",
    "sellDate": "2023-06-28",
    "inStock": true,
    "quantity": 14,
    "progress": 4,
    "rating": 2
  },
  {
    "id": "97-3df0d0",
    "company": "Dognost",
    "country": "Namibia",
    "product": "Ellis",
    "sellDate": "2023-02-09",
    "inStock": false,
    "quantity": 6,
    "progress": 1,
    "rating": 2
  },
  {
    "id": "06-7066f8",
    "company": "Metroz",
    "country": "Mayotte",
    "product": "Wright",
    "sellDate": "2023-01-03",
    "inStock": true,
    "quantity": 66,
    "progress": 1,
    "rating": 2
  },
  {
    "id": "64-c6dd34",
    "company": "Isologia",
    "country": "Malaysia",
    "product": "Mosley",
    "sellDate": "2023-06-27",
    "inStock": true,
    "quantity": 7,
    "progress": 1,
    "rating": 5
  },
  {
    "id": "3c-544b3f",
    "company": "Trasola",
    "country": "France",
    "product": "Neal",
    "sellDate": "2023-04-14",
    "inStock": true,
    "quantity": 81,
    "progress": 1,
    "rating": 4
  },
  {
    "id": "4e-ba61c7",
    "company": "Comtrek",
    "country": "Armenia",
    "product": "Hutchinson",
    "sellDate": "2023-09-06",
    "inStock": true,
    "quantity": 4,
    "progress": 3,
    "rating": 2
  },
  {
    "id": "77-e86ac0",
    "company": "Gaptec",
    "country": "Portugal",
    "product": "Copeland",
    "sellDate": "2023-10-15",
    "inStock": false,
    "quantity": 15,
    "progress": 2,
    "rating": 3
  },
  {
    "id": "05-6263a9",
    "company": "Paprikut",
    "country": "Bangladesh",
    "product": "Mendoza",
    "sellDate": "2023-10-10",
    "inStock": false,
    "quantity": 44,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "8c-cf91dc",
    "company": "Bleeko",
    "country": "Qatar",
    "product": "Horne",
    "sellDate": "2023-07-13",
    "inStock": false,
    "quantity": 40,
    "progress": 4,
    "rating": 5
  },
  {
    "id": "c0-3b1237",
    "company": "Interfind",
    "country": "Slovenia",
    "product": "Stein",
    "sellDate": "2023-08-29",
    "inStock": true,
    "quantity": 28,
    "progress": 4,
    "rating": 3
  },
  {
    "id": "df-08a63a",
    "company": "Corecom",
    "country": "Virgin Islands (US)",
    "product": "Bennett",
    "sellDate": "2023-03-06",
    "inStock": true,
    "quantity": 80,
    "progress": 4,
    "rating": 4
  },
  {
    "id": "fb-51e45c",
    "company": "Jetsilk",
    "country": "Turkmenistan",
    "product": "England",
    "sellDate": "2023-10-14",
    "inStock": false,
    "quantity": 2,
    "progress": 4,
    "rating": 4
  },
  {
    "id": "8d-d9b649",
    "company": "Uncorp",
    "country": "Saint Kitts and Nevis",
    "product": "Vargas",
    "sellDate": "2023-07-22",
    "inStock": false,
    "quantity": 26,
    "progress": 3,
    "rating": 3
  },
  {
    "id": "a5-a0b2b7",
    "company": "Gink",
    "country": "Sao Tome and Principe",
    "product": "King",
    "sellDate": "2023-09-17",
    "inStock": true,
    "quantity": 60,
    "progress": 5,
    "rating": 3
  },
  {
    "id": "aa-036fd9",
    "company": "Irack",
    "country": "Suriname",
    "product": "Heath",
    "sellDate": "2023-06-03",
    "inStock": true,
    "quantity": 45,
    "progress": 1,
    "rating": 3
  },
  {
    "id": "62-dbbb4f",
    "company": "Multiflex",
    "country": "Virgin Islands (British)",
    "product": "Harding",
    "sellDate": "2023-05-03",
    "inStock": true,
    "quantity": 34,
    "progress": 3,
    "rating": 2
  },
  {
    "id": "fe-2da6b1",
    "company": "Elpro",
    "country": "Nigeria",
    "product": "Davis",
    "sellDate": "2023-06-19",
    "inStock": false,
    "quantity": 62,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "c1-89e0db",
    "company": "Balooba",
    "country": "Nicaragua",
    "product": "Roth",
    "sellDate": "2023-03-06",
    "inStock": true,
    "quantity": 21,
    "progress": 5,
    "rating": 1
  },
  {
    "id": "04-acbe7d",
    "company": "Aquasseur",
    "country": "Eritrea",
    "product": "Riley",
    "sellDate": "2023-05-28",
    "inStock": true,
    "quantity": 42,
    "progress": 1,
    "rating": 2
  },
  {
    "id": "c5-1bc535",
    "company": "Exospeed",
    "country": "Niger",
    "product": "Good",
    "sellDate": "2023-04-27",
    "inStock": false,
    "quantity": 96,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "c7-36ebc8",
    "company": "Helixo",
    "country": "Nepal",
    "product": "Vasquez",
    "sellDate": "2023-01-03",
    "inStock": false,
    "quantity": 42,
    "progress": 3,
    "rating": 4
  },
  {
    "id": "59-7c1f1e",
    "company": "Exosis",
    "country": "Mongolia",
    "product": "Pearson",
    "sellDate": "2023-05-25",
    "inStock": true,
    "quantity": 26,
    "progress": 5,
    "rating": 5
  }
];


export default data;

