/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppLogo: typeof import('./src/app/components/widgets/AppLogo.vue')['default']
    CookiesConsent: typeof import('./src/app/components/CookiesConsent.vue')['default']
    EmailRendererComponent: typeof import('./src/app/components/EmailRendererComponent.vue')['default']
    GenderRendererComponent: typeof import('./src/app/components/GenderRendererComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
